### ISSUE TITLE
Tensor g1 and x1 are different sizes when using the dataloader for reference data

### ISSUE THREAD

**Issue by JakeMassmann** [delta6189/Anime-Sketch-Colorizer#2]
I'm not sure if this is an implementation mistake, but when I tried reproducing the results in `test.ipynb`, I get a tensor mismatch during `refer_batch = next(iter(refer_loader))`. Do you know what this could be?

**The Script:**
```
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    if device == 'cuda':
        print("The gpu to be used : {}".format(torch.cuda.get_device_name(0)))
    else:
        print("No gpu detected")

    with torch.no_grad():
        netC2S = mymodels.Color2Sketch(pretrained=True).to(device)
        netC2S.eval()

    # Validation
    # TODO - Get Seperate Validation Data
    print('Loading Validation data...', end=' ')
    val_transforms = TF.Compose([
        TF.Resize(512),
    ])
    val_imagefolder = dataloader.PairImageFolder('../training/data/', val_transforms, netC2S, NUM_CLUSTERS)
    val_loader = torch.utils.data.DataLoader(val_imagefolder, batch_size=BATCH_SIZE, shuffle=False)
    print("Done!")
    print("Validation data size : {}".format(len(val_imagefolder)))

    # Test
    print('Loading Test data...', end=' ')
    test_transforms = TF.Compose([
        TF.Resize(512),
    ])
    test_imagefolder = dataloader.GetImageFolder('../training/data/', test_transforms, netC2S, NUM_CLUSTERS)
    test_loader = torch.utils.data.DataLoader(test_imagefolder, batch_size=BATCH_SIZE, shuffle=False)
    print("Done!")
    print("Test data size : {}".format(len(test_imagefolder)))

    # Reference
    print('Loading Reference data...', end=' ')
    refer_transforms = TF.Compose([
        TF.Resize(512),
    ])
    refer_imagefolder = dataloader.GetImageFolder('../training/data/', refer_transforms, netC2S, NUM_CLUSTERS)
    refer_loader = torch.utils.data.DataLoader(refer_imagefolder, batch_size=BATCH_SIZE, shuffle=False)
    refer_batch = next(iter(refer_loader))
    print("Done!")
    print("Reference data size : {}".format(len(refer_imagefolder)))
```

**Output:**
```
No gpu detected
Loading pretrained Color2Sketch model... Done!
Loading Validation data... Done!
Validation data size : 44969
Loading Test data... Done!
Test data size : 44969
Loading Reference data... Traceback (most recent call last):
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\data_handler.py", line 220, in <module>
    main()
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\data_handler.py", line 197, in main
    try_model()
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\data_handler.py", line 149, in try_model
    refer_batch = next(iter(refer_loader))
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\dataloader.py", line 165, in __getitem__
    img_edge = self.sketch_net(img.unsqueeze(0).to(self.device)).squeeze().permute(1, 2, 0).cpu().numpy()
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\mymodels.py", line 236, in forward
    output = self.decoder(encode)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\mymodels.py", line 183, in forward
    x5 = self.Att5(g=x, x=x5)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Jake\Desktop\Repositories\MangAI\training\mymodels.py", line 94, in forward
    psi = self.relu(g1 + x1)
RuntimeError: The size of tensor a (36) must match the size of tensor b (35) at non-singleton dimension 2

Process finished with exit code 1
```

**Comment by delta6189** [comment]
It is probably the image size problem. The model is trained and evaluted on 512x512. Please check whether the size of the input image has been converted to 512x512 correctly.

The code which resize the image is written on `GetImageFolder` class of `dataloader.py`. Here is the specific code.

```
    def __getitem__(self, index):
        path, label = self.imgs[index]
        img = self.loader(path)
        img = np.asarray(img)
        img = self.transform(img)
        color_palette = color_cluster(img, nclusters=self.ncluster)
        img = self.make_tensor(img)
```

On this code, `img = self.transform(img)` resize the input image via `TF.resize(512)` transform. For some reason, it is possible that the part did not work properly. Please check the relevant part.

Thank you.

**Comment by delta6189** [comment]
Another solution is to bypass the `netC2S`. The issue occur while converting reference image to sketch image but what we need from reference image is only colors of image. Thus, by modifying `GetImageFolder` class, You can make the reference image not pass through the `netC2S` and the issue will not occur.

**Comment by JakeMassmann** [comment]
> It is probably the image size problem. The model is trained and evaluted on 512x512. Please check whether the size of the input image has been converted to 512x512 correctly.
> 
> The code which resize the image is written on `GetImageFolder` class of `dataloader.py`. Here is the specific code.
> 
> ```
>     def __getitem__(self, index):
>         path, label = self.imgs[index]
>         img = self.loader(path)
>         img = np.asarray(img)
>         img = self.transform(img)
>         color_palette = color_cluster(img, nclusters=self.ncluster)
>         img = self.make_tensor(img)
> ```
> 
> On this code, `img = self.transform(img)` resize the input image via `TF.resize(512)` transform. For some reason, it is possible that the part did not work properly. Please check the relevant part.
> 
> Thank you.

Works great after I replaced the transforms for validation, test, and reference with this. And thank you for responding so quickly!

```
refer_transforms = TF.Compose([
    TF.Resize([512, 512]),
])
```
